export default {
  battleVictoryMusic: '1-06 Victory Fanfare.mp3',
  bossBattleMusicPart1: 'boss-battle1.m4a',
  bossBattleMusicPart2: 'boss-battle2.m4a',
  cureMagicFX: 'healingSpell.mp3',
  cursorMovementFX: 'cursor.mp3',
  enemyAttackFX: 'swipe.mp3',
  fireMagicFX: 'fire1.mp3',
  gameOverMusic: '19 Game Over.mp3',
  heroAttackFX: 'sword-slash.mp3',
  iceMagicFX: 'ice2.m4a',
  introMusic: '3-16 The Prelude.mp3',
  lightningMagicFX: 'lightning1.m4a',
  normalBattleMusic: '1-05 Battle.mp3',
  overworldMusic: "2-01 Terra's Theme.mp3",
}
